### ISSUE TITLE
Installation directories

### ISSUE THREAD

**Issue by KobachaiD** [ficonsulting/RInno#11]
Hi,
I am using RInno to compile my Shiny app and wish to install the resulting program on a communal PC on campus. Compilation was fine but installation was not successful as it was trying to install R in drive C. This is not possible as I do not have administration right to this section of the computer. I wonder whether it is possible to direct R installation to somewhere else (e.g. Document).

Thanks in advance for your help,
Kobchai

**Comment by Dripdrop12** [comment]
Hi @KobachaiD,
What does the communal PC look like? When you sign in, does everyone have their own Windows log-in? RInno defaults to installing in My Documents, but it sounds like My Documents may be in a strange location. 

In order to trouble shoot this issue, you can try different `default_dir` arguments like each users' desktop:
```
create_app(
	app_name    = "myapp",
	app_dir     = "path/to/myapp",
	default_dir = "userdesktop")
```
This argument tells RInno where you would like the Shiny app to be installed on each user's computer. However, you may need to customize this further depending on how your communal PC is configured.

**Comment by Dripdrop12** [comment]
You also may want to have a conversation with IT about the communal PC's permissions because you are usually free to work in My Documents, even on a communal PC.

**Comment by Dripdrop12** [comment]
@chasemc are you referring to when `compile_iss` is called? Or when installation files are added with `system.file`?

**Comment by chasemc** [comment]
I'm not sure of all the details as the app was run and installed by a user, but somehow the app was installed on a different drive than R got installed to. Then for some reason system(cmd) calls were flagging 127.  I cannot replicate this on my own computer so cannot yet claim as a RInno issue.

**Comment by Dripdrop12** [comment]
It could be two things:

1. the command is not found (RInno path-based bug)
2. the command's dependency is not found (application configuration bug)
