### ISSUE TITLE
Rinno doesn't support app.R

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#33]
It works fine with ui.r and server.r files but that is the old way of writing codes. Now I and most people use modularized code which is very hard to maintain in ui.r and server.r files.

as the code base increases and you create more and more modularized app. the 2 file modal is very hard to maintain.

Thus please let us use app.r or a single file approach as well. Please.

**Comment by Dripdrop12** [comment]
@vikram-rawat, RStudio states that app.R "is more appropriate for smaller applications; for larger applications, you may find that having separate ui.R and server.R files makes your code easier to manage." - [article](http://shiny.rstudio.com/articles/app-formats.html)

They argue that larger apps benefit from separate ui.R and server.R files because they provide a clear separation of concerns between the server calculations and the user interface components. If something should be available to both the user interface and server, you should put it in global.R, which will load that object into your global environment.

I just ran a test with an app.R file in a clean directory:
```
## app.R ##
server <- function(input, output) {
  output$distPlot <- renderPlot({
    hist(rnorm(input$obs), col = 'darkgray', border = 'white')
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput("obs", "Number of observations:", min = 10, max = 500, value = 100)
    ),
    mainPanel(plotOutput("distPlot"))
  )
)

shinyApp(ui = ui, server = server)
```

Then I ran:
```
require(RInno)
create_app("myapp")
compile_iss()
```
It worked as expected. Maybe you are having another issue?

**Comment by vikram-rawat** [comment]
Sorry to bother you somehow it didn't work for me. I thought I should let you know. Thanks for the response anyway

**Comment by Dripdrop12** [comment]
Can you share your app.R code and the RInno code you used to compile your app? Maybe I can help you trouble shoot it.
