### ISSUE TITLE
Is there any way to include bioconductor package dependency ?

### ISSUE THREAD

**Issue by hcji** [ficonsulting/RInno#41]
Is there any way to include bioconductor package dependency ?
I try to add `remotes = c('bioc::3.5/PackageName')`  into create_app function, but it seems not work ?

**Comment by Dripdrop12** [comment]
`remotes` is for Github package dependencies, so if the bioconductor package is on Github, the first step is to find it's Github repo. For example, a4Core has a mirror at https://github.com/Bioconductor-mirror/a4Core, so you can include it with `remotes = "Bioconductor-mirror/a4Core"`.

If the package is on CRAN, than you can add it to the `pkgs` argument. 

Because all Bioconductor packages have .tag.gz files on their Package Archives - Source Package section, i.e. [a4Core](https://www.bioconductor.org/packages/release/bioc/html/a4Core.html), another option is to download them from source. Place the .tag.gz files in `local_path`, which defaults to "app_dir/local", and add their names to the `locals = "a4Core"` argument.

Bioconductor's non-standard package release and installation process makes it difficult to support their packages explicitly. If more people need direct support for Bioconductor packages, please let us know on this thread!

**Comment by hcji** [comment]
I tried the first method, but failed. Thus, I tried the 'local' way. It sounds it cannot download the dependent package in the local install, so I used packrat. but I got the error massage of '"Some locals match multiple .tar.gz files'.
I check the code, this is because the line of
 ` locals_check <- unlist(lapply(locals, function(x) list.files(file.path(app_dir, local_path), pattern = x)))`
it happens when some package names are similar, like 'plyr' and 'dplyr'.
Can I remove the check temporarily and go on ?

**Comment by Dripdrop12** [comment]
First, locals will not be automatically downloaded. They have to be added by the developer manually. I recommend you clone the package's source code from Github and use `devtools::build()` to create the .tar.gz files. 

That check is there for a reason. If it fails, the application will fail too, so you should not proceed.

For dplyr and plyr, they should be listed as `pkgs` because they are on CRAN. I do not recommend including them as locals. You should also consider replacing plyr with tidyr because plyr is no longer fully supported by RStudio.  

What are the Bioconductor packages with similar names? Maybe we can improve the locals process so that this check can pass.

**Comment by chasemc** [comment]
You can also include the call to install within your app:

For example, for package mzR:

```r
if(!length(grep("mzR",row.names(installed.packages())))){
  if(!length(grep("BiocInstaller",row.names(installed.packages())))){
    source("https://bioconductor.org/biocLite.R")
    biocLite("BiocInstaller",suppressUpdates = T)
    }

  source("https://bioconductor.org/biocLite.R")
  biocLite("mzR",ask=F)
}
```
