### ISSUE TITLE
GPL virality when using RInno

### ISSUE THREAD

**Issue by alamit** [ficonsulting/RInno#46]
I am wondering about licensing issues with apps distributed with RInno.

As from what I could understand, GPL virality does not apply when distributing R packages as the dependencies are not linked at the moment of distribution. [Hadley Wickham's answer on this](https://twitter.com/levithatcher/status/771716687712231424)

However, once distributing an app packaged with RInno, even if the imported packages are installed on the first run of the app, I think one could argue that the app is packaged as one executable and that the app cannot run without the required packages, as the FSF states [here](https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation) then virality of the GPL license would apply.

Because lot of packages on CRAN have license incompatibilities, for example, if one wanted to create a `shiny` app using `shinydashboard` and distribute in an RInno packaged installer, there would be a clear license compatibility issue as `shiny` is GPL-3 only, `shinydashboard` is GPL-2 only, and these licenses are not compatible as stated [here](https://www.gnu.org/licenses/gpl-faq.en.html#v2v3Compatibility). It could become a big issue for people using RInno to distribute applications.

What do you think?

**Comment by Dripdrop12** [comment]
I don't believe GPL virality applies to RInno because it installs packages from CRAN on the end user's computer. The executable does not deliver them as one cohesive piece of software. It just includes the metadata required to manage a shiny application's start up sequence and dependencies. 

RInno organizes the batch sequence to start the app and finds the other software it needs (like a browser), but it does not link to them any more than they are linked to when you library them into any R environment. There are no shared data structures or objects.

I do believe you are correct to dig into the license compatibility of various packages and how they interact with each other. It is an important consideration. Do you have a good definition for "linked"? My understanding is that for two software to be linked, they need to share low-level object and data structures.

There are numerous examples of GPL packages that help connect to proprietary databases in a much more direct way or visualization packages that use JavaScript libraries not licensed under the GPL.

**Comment by Dripdrop12** [comment]
At its core, RInno produces instructions for Inno Setup and configs for the shiny app. Visual Studio and other IDEs help automate configurations and even compile applications as well. There is nothing about RInno's design that is directly linked to other R packages. The closest example is `installr`, which is used to install Inno Setup and other software in the development environment.

The only time where GPL really could be an issue is if you want to build a proprietary system that links with RInno to deliver services to customers. For example, if you wanted to use `RInno::create_app` in the UI of a proprietary system to release shiny apps as .exe files...
