### ISSUE TITLE
Latest dev version > CRAN version leads to error after new user installs

### ISSUE THREAD

**Issue by bthomasbailey** [ficonsulting/RInno#53]
I debated adding a comment to issue #48 , but I think this is actually a slightly different issue. When I used RInno's create_app function to create the .iss file and all other supporting folders and files, including config.cfg, I had a version of shiny that I had installed using devtools::install_github. As such, its version (1.0.5.900) exceeded that of the latest CRAN version (1.0.5). So when RInno called the create_config() function, which in turn called standardize_pkgs(), "shiny": ">=1.0.5.9000" was written to the config file. Then when I switched to a different computer that didn't have shiny installed, when ensure() was called, it tried to use devtools::install_version where repo was set to "http://cran.rstudio.com" and version was set to the required version of "1.0.5.9000." This, of course, results in an error because this version does not exist on CRAN.

For right now, I know I can easily solve the issue by switching back to shiny v. 1.0.5 on my development computer and re-running RInno. Is passing the package name into the "remotes" argument for create_app a solution to this, or is there something else that needs to be done?

**Comment by Dripdrop12** [comment]
I'm glad you broke this out into its own issue because I see it as a different problem. 

Currently, if you would like to include a development version of a package, adding it to the `remotes` argument is the only way to do it. 

Regardless, I think we should have a control which warns you or errors out if the package you are using is ahead of CRAN.  Does that sound like a good solution?
