### ISSUE TITLE
Can we use shinyproxy along with it

### ISSUE THREAD

**Issue by vikram-rawat** [ficonsulting/RInno#58]
It seems like other than Sunny server open source and pro there is something called shinyproxy which can provide much better authentication to the app and speed enhancements too.

Is there a way you can support that in RInno than we can actually get a framework with security. Please don't discard the idea right off. At least ponder on it.

**Comment by Dripdrop12** [comment]
Hi vikram,

We looked into using Shiny Proxy before we started building RInno, so we have had a long time to think about it. Shiny Proxy is more analogous to Shiny Server because it sits on a server and serves up shiny apps to users using Docker images, Apache and the Spring boot framework. If that is how users are going to receive their applications, they don't need RInno. If they are receiving their apps as locally installed programs (RInno), they don't need the server deployment (Shiny Proxy/Shiny Server). Does that make sense?

RInno supports continuous installation via Github/Bitbucket. This allows your apps to update automatically when you push out a new release, hotfix or feature. Check out the [Continuous Installation](https://cran.r-project.org/web/packages/RInno/vignettes/cont-installation.html) vignette for details. 

You can add a layer of security to this deployment method with app tokens and security credentials. However, local shiny apps are not true web applications, so https and some of the other security issues addressed by Shiny Server and Shiny Proxy are not applicable to RInno apps.

**Comment by vikram-rawat** [comment]
Thanks for replying I just wanted to know if this is a viable option and if it might help you. No Issues. Keep up the work.
